spring:
  application:
    name: ProjectFlow

  datasource:
    url: jdbc:postgresql://localhost:5432/project_flow_db
    username: postgres
    password: post-n3Z
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # use 'validate' or 'none' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  flyway:
    enabled: true
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}

server:
  port: 8080
  servlet:
    context-path: /projectflow

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
